### ISSUE TITLE
Ceres Invoice March

### ISSUE THREAD

**Issue by DanijelCBS** [sora-xor/sora-accounting#112]
Available [here](https://github.com/sora-xor/sora-accounting/blob/master/Ceres%20Community%20Memo/Ceres_Blockchain_Solutions_Memo_to_the_SORA_Community_March_2024.pdf)

**Comment by WRRicht3r** [comment]
Available as Democracy Referenda [362](https://sora.subscan.io/referenda/362)

**Comment by WRRicht3r** [comment]
Paid in Full
