### ISSUE TITLE
OpenGov Proposal Decision Deposit

### ISSUE THREAD

**Issue by MishoKanaria** [sora-xor/sora-accounting#124]
In order for our [OpenGov Referenda](https://polkadot.polkassembly.io/referenda/722) to move into the decision phase, we will need a decision deposit of 5,000 DOT. This DOT is refunded at the end of the proposal and can either be used in the future for Coretime or returned to SORA.

A request for 5,000 DOT equivalent in TBCD to be DCA over the next week to account: cnSBr8GHVw6Zd2Ek5qsXrjXfj9DtQnPdnnCxQ4dj3yPjL7CD9

**Comment by MishoKanaria** [comment]
An additional amount of ~$30,000 equivalent in TBCD is requested to cover the remaining [Ceres Invoice](https://github.com/sora-xor/sora-accounting/blob/master/Ceres%20Community%20Memo/Ceres_Blockchain_Solutions_Memo_to_the_SORA_Community_April_2024.pdf) due to the recent price impact.

**Comment by shlavik** [comment]
After unlocking 5000 DOT, XOR will be bought back with them, after which it will be burned?
