### ISSUE TITLE
Treasury for Ceres Blockchain Solutions

### ISSUE THREAD

**Issue by MishoKanaria** [sora-xor/sora-accounting#128]
A treasury for Ceres Blockchain Solutions for April and upcoming May invoice.

Amount: USD$200,000
Account: cnSBr8GHVw6Zd2Ek5qsXrjXfj9DtQnPdnnCxQ4dj3yPjL7CD9

**Comment by WRRicht3r** [comment]
Available as Council Motion

**Comment by WRRicht3r** [comment]
Available as Democracy Referenda [383](https://sora.subscan.io/referenda/383)

**Comment by WRRicht3r** [comment]
Paid in Full
