### ISSUE TITLE
Polkaswap Market Maker Fund

### ISSUE THREAD

**Issue by MishoKanaria** [sora-xor/sora-accounting#133]
USD$4,000 equivalent in XOR is proposed for the Polkaswap Market Maker.
Account: cnRabkHhUybUhFxiywvzH7BDcSsK2iMxN8nRH3hB6CxUxtQPJ

**Comment by WRRicht3r** [comment]
Available as Council Motion [480](https://sora.subscan.io/council/480)

**Comment by WRRicht3r** [comment]
Available as Democracy Referenda [390](https://sora.subscan.io/referenda/390)

**Comment by WRRicht3r** [comment]
Paid in Full
