### ISSUE TITLE
SORA Trust Treasury

### ISSUE THREAD

**Issue by WRRicht3r** [sora-xor/sora-accounting#169]
Treasury expansion to mint 5000 PUSSY to cnWP3DYJ5afJZaZsvJ84REqBjqLDRbknejXtCqzj5DC6eQX1R

**Comment by MishoKanaria** [comment]
Available as motion [579](https://sora.subscan.io/council/579)

**Comment by MishoKanaria** [comment]
Available as referendum [482](https://sora.subscan.io/referenda/482)

**Comment by MishoKanaria** [comment]
Referendum has been successful
