### ISSUE TITLE
SORA Trust Treasury $PUSSY

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora-accounting#171]
Treasury expansion to mint 1,000,000 PUSSY to cnWP3DYJ5afJZaZsvJ84REqBjqLDRbknejXtCqzj5DC6eQX1R

**Comment by MishoKanaria** [comment]
Available as motion [587](https://sora.subscan.io/council/587)

**Comment by MishoKanaria** [comment]
Available as referendum [489](https://sora.subscan.io/referenda/489)

**Comment by MishoKanaria** [comment]
Referendum has been successful
