### ISSUE TITLE
Band Relayer Fees

### ISSUE THREAD

**Issue by MishoKanaria** [sora-xor/sora-accounting#182]
100M XOR, equivalent in VXOR are required for quarterly Band Relayer fees. Any leftover XOR from the conversion will be carried forward.

XOR should be paid by the trust to cnStiKpiSGzwfdYHx9qJCduSpVKQ4A81x2XEhULXSWF5NYe44

**Comment by MishoKanaria** [comment]
Available as Council Motion [648](https://sora.subscan.io/council/648)

**Comment by WRRicht3r** [comment]
Relayer fees were not enough for the entire quarter. 650M XOR equivalent in vXOR are needed. 
XOR should be paid by the trust to cnStiKpiSGzwfdYHx9qJCduSpVKQ4A81x2XEhULXSWF5NYe44

**Comment by MishoKanaria** [comment]
Available as referendum [557](https://sora.subscan.io/referenda/557)

**Comment by MishoKanaria** [comment]
Referendum Successful
