### ISSUE TITLE
Proposal to change file name format

### ISSUE THREAD

**Issue by shlavik** [sora-xor/sora-accounting#23]
For better convenience and efficiency in maintaining this repository, and to simplify the search for files when there are many of them, especially given the default file name sorting, I suggest we change the file naming template.
Specifically, instead of:
SORA Community Memo-July-2023.pdf
prioritize the year, like this:
SORA Community Memo-2023-July.pdf
This way, it will be easier to visually search for files, as they'll be grouped by year.
What are your thoughts on this?

![image](https://github.com/sora-xor/sora-accounting/assets/2076748/c4f09dea-1e33-4249-9193-8962335078c6)

**Comment by WRRicht3r** [comment]
Hello, thank you for the input. I will work on implementing.

**Comment by WRRicht3r** [comment]
Hello, implemented in the latest PR
