### ISSUE TITLE
SORA CEX Treasury

### ISSUE THREAD

**Issue by WRRicht3r** [sora-xor/sora-accounting#44]
As liquidity for CEX, a treasury containing the following amounts is needed;

2M XOR for MM Gate
1.8M XOR for CEX listing
1M XOR for CEX MM

**Comment by WRRicht3r** [comment]
Council motion available [here](https://sora.subscan.io/council/357)

**Comment by WRRicht3r** [comment]
Hi @Grugonion, in simple terms, MM are the tokens that people buy from CEX.

**Comment by Nolan730** [comment]
> Can you explain why we need MM, what the benefits of MM is?

Its forced by CEX. Its like jumpstart for orderbooks since people wont be able to trade until people put orders and make orderbook full.

**Comment by WRRicht3r** [comment]
Available as governance referendum [288](https://sora.subscan.io/referenda/288)

**Comment by WRRicht3r** [comment]
Paid in full
