### ISSUE TITLE
Ceres invoice December

### ISSUE THREAD

**Issue by DanijelCBS** [sora-xor/sora-accounting#76]
Available [here](https://github.com/sora-xor/sora-accounting/blob/master/Ceres%20Community%20Memo/Ceres_Blockchain_Solutions_Memo_to_the_SORA_Community_December_2023.pdf)

**Comment by WRRicht3r** [comment]
Available as council motion [392](https://sora.subscan.io/council/392)

**Comment by WRRicht3r** [comment]
Available as governance referenda [317](https://sora.subscan.io/referenda/317)
