### ISSUE TITLE
Polkadot Market Maker Liquidity Fund Request Feb 24

### ISSUE THREAD

**Issue by WRRicht3r** [sora-xor/sora-accounting#88]
Request available as PR [86](https://github.com/sora-xor/sora-accounting/pull/86)

**Comment by WRRicht3r** [comment]
Available as Council Motion [412](https://sora.subscan.io/council/412)

**Comment by shlavik** [comment]
> Request available as PR [86](https://github.com/sora-xor/sora-accounting/pull/86)

this is about Ceres 🤷‍♂️ [Ceres January 2024 #86](https://github.com/sora-xor/sora-accounting/pull/86)

**Comment by WRRicht3r** [comment]
No, this is something else. This is a request for a Market Maker.

**Comment by WRRicht3r** [comment]
Paid in Full
